In [1]:
import pandas as pd
import numpy as np

In [ ]:
dm=pd.read_excel(r"C:\Users\anadi\Desktop\Direct Marketing.xlsx")

In [ ]:
dm.shape

In [5]:
dm.head()

,AmountSpent,Age,Gender,OwnHome,Married,Location,Salary,Children,Catalogs,History
0,755,Old,Female,Own,Single,Far,47500,0,6,High
1,1318,Middle,Male,Rent,Single,Close,63600,0,6,High
2,296,Young,Female,Rent,Single,Close,13500,0,18,Low
3,2436,Middle,Male,Own,Married,Close,85600,1,18,High
4,1304,Middle,Female,Own,Single,Close,68400,0,12,High

In [9]:
dm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   AmountSpent  1000 non-null   int64
 1   Age          1000 non-null   object
 2   Gender       1000 non-null   object
 3   OwnHome      1000 non-null   object
 4   Married      1000 non-null   object
 5   Location     1000 non-null   object
 6   Salary       1000 non-null   int64
 7   Children     1000 non-null   int64
 8   Catalogs     1000 non-null   int64
 9   History      1000 non-null   object
dtypes: int64(4), object(6)
memory usage: 78.3+ KB

In [7]:
dm_cat=dm.select_dtypes(object)

In [13]:
dm_num=dm.select_dtypes(int)

In [ ]:
dm_num

In [9]:
dm_cat

        Age  Gender OwnHome  Married Location     History
0       Old  Female     Own   Single      Far        High
1    Middle    Male    Rent   Single    Close        High
2     Young  Female    Rent   Single    Close         Low
3    Middle    Male     Own  Married    Close        High
4    Middle  Female     Own   Single    Close        High
..      ...     ...     ...      ...      ...         ...
995   Young  Female    Rent   Single    Close  First time
996  Middle    Male    Rent   Single      Far  First time
997     Old    Male     Own   Single    Close      Medium
998  Middle    Male     Own  Married    Close      Medium
999   Young    Male    Rent  Married    Close      Medium

[1000 rows x 6 columns]

In [11]:
dummies = pd.get_dummies(dm_cat)

In [13]:
dummies

,Age_Middle,Age_Old,Age_Young,Gender_Female,Gender_Male,OwnHome_Own,OwnHome_Rent,Married_Married,Married_Single,Location_Close,Location_Far,History_First time,History_High,History_Low,History_Medium
0,False,True,False,True,False,True,False,False,True,False,True,False,True,False,False
1,True,False,False,False,True,False,True,False,True,True,False,False,True,False,False
2,False,False,True,True,False,False,True,False,True,True,False,False,False,True,False
3,True,False,False,False,True,True,False,True,False,True,False,False,True,False,False
4,True,False,False,True,False,True,False,False,True,True,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,True,True,False,False,True,False,True,True,False,True,False,False,False
996,True,False,False,False,True,False,True,False,True,False,True,True,False,False,False
997,False,True,False,False,True,True,False,False,True,True,False,False,False,False,True
998,True,False,False,False,True,True,False,True,False,True,False,False,False,False,True
999,False,False,True,False,True,False,True,True,False,True,False,False,False,False,True

In [15]:
dm1=pd.concat([dm,dummies],axis="columns")

In [17]:
dm1.head()

,AmountSpent,Age,Gender,OwnHome,Married,Location,Salary,Children,Catalogs,History,...,OwnHome_Own,OwnHome_Rent,Married_Married,Married_Single,Location_Close,Location_Far,History_First time,History_High,History_Low,History_Medium
0,755,Old,Female,Own,Single,Far,47500,0,6,High,...,True,False,False,True,False,True,False,True,False,False
1,1318,Middle,Male,Rent,Single,Close,63600,0,6,High,...,False,True,False,True,True,False,False,True,False,False
2,296,Young,Female,Rent,Single,Close,13500,0,18,Low,...,False,True,False,True,True,False,False,False,True,False
3,2436,Middle,Male,Own,Married,Close,85600,1,18,High,...,True,False,True,False,True,False,False,True,False,False
4,1304,Middle,Female,Own,Single,Close,68400,0,12,High,...,True,False,False,True,True,False,False,True,False,False

In [19]:
dm2=dm1.drop(["Age","Gender","OwnHome","Married","Location","History"],axis="columns")

In [21]:
dm2.head()

,AmountSpent,Salary,Children,Catalogs,Age_Middle,Age_Old,Age_Young,Gender_Female,Gender_Male,OwnHome_Own,OwnHome_Rent,Married_Married,Married_Single,Location_Close,Location_Far,History_First time,History_High,History_Low,History_Medium
0,755,47500,0,6,False,True,False,True,False,True,False,False,True,False,True,False,True,False,False
1,1318,63600,0,6,True,False,False,False,True,False,True,False,True,True,False,False,True,False,False
2,296,13500,0,18,False,False,True,True,False,False,True,False,True,True,False,False,False,True,False
3,2436,85600,1,18,True,False,False,False,True,True,False,True,False,True,False,False,True,False,False
4,1304,68400,0,12,True,False,False,True,False,True,False,False,True,True,False,False,True,False,False

In [23]:
x=dm2.iloc[:,1:19]

In [25]:
x

,Salary,Children,Catalogs,Age_Middle,Age_Old,Age_Young,Gender_Female,Gender_Male,OwnHome_Own,OwnHome_Rent,Married_Married,Married_Single,Location_Close,Location_Far,History_First time,History_High,History_Low,History_Medium
0,47500,0,6,False,True,False,True,False,True,False,False,True,False,True,False,True,False,False
1,63600,0,6,True,False,False,False,True,False,True,False,True,True,False,False,True,False,False
2,13500,0,18,False,False,True,True,False,False,True,False,True,True,False,False,False,True,False
3,85600,1,18,True,False,False,False,True,True,False,True,False,True,False,False,True,False,False
4,68400,0,12,True,False,False,True,False,True,False,False,True,True,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,19400,1,18,False,False,True,True,False,False,True,False,True,True,False,True,False,False,False
996,40500,1,18,True,False,False,False,True,False,True,False,True,False,True,True,False,False,False
997,44800,0,24,False,True,False,False,True,True,False,False,True,True,False,False,False,False,True
998,79000,2,18,True,False,False,False,True,True,False,True,False,True,False,False,False,False,True
999,53600,1,24,False,False,True,False,True,False,True,True,False,True,False,False,False,False,True

In [27]:
y=dm.iloc[:,0:1]

In [29]:
y

     AmountSpent
0            755
1           1318
2            296
3           2436
4           1304
..           ...
995          384
996         1073
997         1417
998          671
999          973

[1000 rows x 1 columns]

In [31]:
import sklearn

In [33]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=24)

In [41]:
xtrain.shape

(700, 18)

In [43]:
ytrain.shape

(700, 1)

In [ ]:
xtest.shape

In [ ]:
ytest.shape

In [35]:
from sklearn import linear_model

In [37]:
reg=linear_model.LinearRegression()

In [39]:
reg.fit(xtrain,ytrain)

LinearRegression()

In [41]:
ypred=reg.predict(xtest)

In [43]:
ypred

array([[ 7.95676630e+02],
       [ 5.62452881e+02],
       [ 4.85303920e+02],
       [-1.45749504e+02],
       [ 5.19877574e+01],
       [ 5.06513517e+02],
       [ 1.16366431e+03],
       [-1.28870107e+01],
       [ 3.72101168e+02],
       [ 1.36987206e+03],
       [ 9.35451326e+02],
       [-2.40581529e+02],
       [ 2.12175604e+03],
       [ 1.33014495e+03],
       [ 1.57003376e+02],
       [ 1.31925728e+03],
       [ 2.49035141e+03],
       [ 4.58570773e+02],
       [ 7.13667237e+02],
       [ 1.57109200e+03],
       [ 1.19395133e+03],
       [ 4.80760121e+02],
       [ 8.98626229e+02],
       [-1.83300283e+02],
       [ 1.73929674e+03],
       [-6.68244562e+01],
       [ 2.13524222e+03],
       [ 3.23520420e+03],
       [ 7.34713527e+02],
       [ 1.51564425e+03],
       [ 1.49810730e+03],
       [ 1.22850513e+03],
       [ 2.77361410e+03],
       [ 2.26830526e+03],
       [ 2.00109192e+03],
       [ 1.86558497e+03],
       [ 9.15486969e+02],
       [ 1.35039570e+03],
       [ 1.38981448e+03],
       [ 2.73876645e+03],
       [ 9.31440323e+02],
       [ 2.46795738e+03],
       [ 4.07742572e+02],
       [ 1.43762529e+03],
       [ 8.94696106e+02],
       [ 1.25073702e+03],
       [ 1.08388966e+03],
       [ 1.91121145e+03],
       [ 1.90391126e+03],
       [ 4.48148590e+02],
       [ 3.45991194e+02],
       [ 8.54960978e+02],
       [ 1.87274356e+03],
       [ 7.36885874e+02],
       [ 2.41643788e+03],
       [ 1.82477819e+03],
       [ 5.70286935e+02],
       [ 7.17408031e+02],
       [ 1.25574998e+03],
       [-2.97087730e+02],
       [ 9.91765626e+02],
       [ 1.60190889e+02],
       [ 3.88556205e+02],
       [ 1.92588413e+03],
       [ 3.27116748e+03],
       [ 3.60640177e+02],
       [ 1.99396952e+03],
       [ 6.63191247e+02],
       [ 1.13546190e+03],
       [ 1.10690474e+03],
       [ 1.93382338e+03],
       [ 5.03877983e+02],
       [ 9.74620359e+02],
       [ 3.58581737e+02],
       [ 1.26419039e+03],
       [ 5.46058296e+02],
       [ 6.33770095e+02],
       [ 2.79723651e+03],
       [ 3.09953988e+02],
       [ 1.31016771e+03],
       [ 2.08319619e+03],
       [ 6.51094420e+02],
       [ 1.63175183e+03],
       [ 6.45187979e+02],
       [ 6.04476628e+02],
       [ 6.45824698e+02],
       [ 2.23584589e+03],
       [ 2.17684274e+03],
       [ 1.99967688e+03],
       [-3.80601832e+02],
       [ 2.57564143e+03],
       [ 2.32805454e+03],
       [-2.07559007e+02],
       [ 1.31925728e+03],
       [ 3.34164803e+02],
       [ 5.99707486e+02],
       [ 1.51319229e+02],
       [ 2.58699136e+03],
       [ 1.67051601e+03],
       [ 2.53685269e+03],
       [ 7.48294222e+02],
       [ 2.35785035e+03],
       [ 8.31490429e+02],
       [ 7.48722186e+02],
       [ 1.95940525e+03],
       [ 3.73930710e+01],
       [ 1.18843674e+03],
       [-3.22841678e+02],
       [ 2.09019301e+03],
       [ 1.46863760e+02],
       [ 2.73478699e+03],
       [ 2.37797933e+02],
       [ 1.10467091e+03],
       [ 2.20831602e+03],
       [ 5.13894708e+02],
       [ 1.60563828e+03],
       [ 1.68139558e+03],
       [ 8.95208659e+01],
       [ 1.11635390e+03],
       [ 2.14495086e+03],
       [ 2.88877680e+02],
       [ 2.65200759e+03],
       [ 1.43074093e+03],
       [ 1.42988684e+03],
       [ 1.60890971e+03],
       [ 2.16324719e+03],
       [ 1.48581080e+03],
       [ 1.09613828e+03],
       [ 2.44440816e+03],
       [ 7.96411776e+02],
       [ 9.54456490e+02],
       [ 2.46676857e+03],
       [ 9.12080454e+02],
       [ 2.62153961e+03],
       [ 2.55983730e+03],
       [ 3.26705905e+01],
       [ 1.48386072e+03],
       [ 5.64780455e+01],
       [ 1.65982009e+03],
       [ 5.70034695e+02],
       [-1.76495026e+02],
       [ 1.01191932e+03],
       [ 1.95543719e+03],
       [ 2.48004956e+03],
       [ 4.89845691e+02],
       [ 5.71866467e+02],
       [ 4.04385126e+02],
       [ 1.08724976e+03],
       [ 1.16710853e+03],
       [ 8.09896105e+02],
       [ 2.29044835e+02],
       [ 1.58727346e+03],
       [-2.94346654e+01],
       [ 1.33804777e+03],
       [ 5.42030791e+02],
       [ 1.73437980e+02],
       [ 1.08273967e+03],
       [ 4.89914135e+02],
       [ 1.12271874e+03],
       [ 1.11069896e+03],
       [ 1.67158399e+03],
       [ 1.47093564e+03],
       [ 5.33607506e+02],
       [ 6.80161463e+02],
       [ 1.82109708e+03],
       [ 5.85318440e+02],
       [ 7.00598216e+02],
       [ 2.16707431e+03],
       [-4.73373197e+01],
       [ 7.78708650e+02],
       [ 1.17641300e+03],
       [ 1.88831512e+02],
       [ 3.26496139e+02],
       [ 2.81740661e+03],
       [ 2.12951912e+03],
       [ 9.66751835e+02],
       [ 7.76726090e+02],
       [ 1.25002992e+03],
       [ 2.02536285e+03],
       [ 2.90265813e+03],
       [ 2.06652606e+02],
       [ 2.68896596e+03],
       [ 7.91248272e+02],
       [ 3.83834617e+02],
       [ 1.67717111e+03],
       [ 1.39830071e+03],
       [ 1.07830124e+03],
       [ 1.13445364e+03],
       [ 1.88035808e+03],
       [ 2.00250300e+03],
       [ 1.72021277e+03],
       [ 1.28867168e+03],
       [ 4.68671894e+02],
       [ 1.18752507e+03],
       [ 5.77514839e+01],
       [ 2.15242659e+03],
       [ 1.44526214e+03],
       [ 1.31417975e+03],
       [ 1.17254039e+03],
       [-2.95953401e+02],
       [ 3.69564587e+03],
       [ 7.95893024e+02],
       [ 1.07388413e+03],
       [ 2.65206508e+02],
       [ 1.88269616e+03],
       [ 5.77158820e+01],
       [ 1.59524748e+03],
       [ 8.97092175e+02],
       [ 4.02341830e+02],
       [ 1.53887784e+03],
       [ 2.40605631e+03],
       [ 9.25692021e+02],
       [ 1.82691856e+03],
       [ 2.61617871e+03],
       [ 2.94998201e+03],
       [ 2.18429276e+03],
       [ 1.10180976e+03],
       [ 1.54880892e+03],
       [ 1.68439273e+03],
       [ 2.11249177e+03],
       [ 1.86156770e+03],
       [ 2.04442949e+03],
       [ 2.93828429e+02],
       [ 4.75036867e+02],
       [ 1.29312728e+03],
       [ 6.60720268e+02],
       [ 8.57574791e+02],
       [ 1.66756672e+03],
       [ 1.12145159e+03],
       [ 1.77329430e+03],
       [ 2.21352389e+03],
       [ 2.99861698e+01],
       [ 2.35533788e+03],
       [ 6.69480725e+02],
       [ 1.24508719e+03],
       [ 1.76593682e+03],
       [ 2.38219225e+03],
       [ 7.43314368e+02],
       [ 1.23659978e+03],
       [-1.19213780e+02],
       [ 2.24103363e+03],
       [ 4.58091481e+02],
       [ 7.86554905e+02],
       [ 2.46526541e+03],
       [ 8.45302524e+02],
       [ 2.72180959e+02],
       [ 1.92588648e+03],
       [ 3.31014873e+03],
       [-8.32537140e-01],
       [ 6.95584696e+02],
       [ 1.23305677e+03],
       [ 3.07727790e+03],
       [ 1.22187295e+03],
       [ 5.19632275e+02],
       [ 6.19467190e+02],
       [ 6.71704968e+02],
       [ 3.18450081e+02],
       [ 2.06328828e+03],
       [ 1.74495308e+03],
       [ 1.29553550e+03],
       [ 1.18306960e+03],
       [ 1.76097125e+02],
       [ 8.44476829e+02],
       [ 7.71032655e+02],
       [ 1.33798018e+03],
       [ 1.47475913e+03],
       [ 7.30836653e+02],
       [ 4.35105797e+02],
       [ 1.03951171e+03],
       [ 1.17064638e+03],
       [ 2.00678384e+03],
       [ 2.48271878e+03],
       [ 1.73922611e+03],
       [ 8.01598778e+02],
       [ 6.47097353e+02],
       [ 2.91301037e+02],
       [ 4.64858015e+02],
       [ 6.28459972e+02],
       [ 1.85104225e+03],
       [ 1.93780390e+03],
       [ 3.43888224e+02],
       [ 1.49861557e+02],
       [ 7.29578955e+02],
       [ 4.61675984e+02],
       [ 8.56274739e+02],
       [ 8.82502557e+02],
       [ 1.72914166e+03],
       [ 8.75840981e+02],
       [ 1.58655653e+03],
       [ 1.98735766e+03],
       [ 1.51475342e+03],
       [ 2.74819507e+03],
       [ 2.68817221e+03],
       [ 1.36446022e+03],
       [ 1.00426201e+03],
       [ 6.13112591e+02],
       [ 1.77261908e+03],
       [ 1.43071382e+03],
       [ 1.99206015e+03],
       [ 3.16759629e+02]])

In [45]:
import sklearn.metrics as metrics

In [47]:
print("Coefficients:",reg.coef_)
print("Intercept:",reg.intercept_)

Coefficients: [[ 1.90937488e-02 -1.48294521e+02  4.24042945e+01 -3.76422993e+01
   5.72241327e+01 -1.95818335e+01  3.62415301e+01 -3.62415301e+01
   9.86721347e+00 -9.86721347e+00 -3.16529871e+01  3.16529871e+01
  -2.18525271e+02  2.18525271e+02  2.07469023e+02  1.94440710e+02
  -1.85151913e+02 -2.16757820e+02]]
Intercept: [-264.06854335]

In [49]:
r2 = metrics.r2_score(ytest,ypred)

In [51]:
r2

0.7727344531050795

In [53]:
mae = metrics.mean_absolute_error(ytest, ypred)
mse = metrics.mean_squared_error(ytest, ypred)

In [55]:
mae

338.1566772504449

In [67]:
mse

214632.34101404456

In [57]:
m = np.mean(ytest)

In [59]:
d = ytest-m

In [61]:
mae_base = np.mean(abs(d))
mse_base = np.mean(d**2)

In [75]:
mae_base

766.6349333333333

In [ ]:
mse_base

In [ ]:
reg.predict([[30,0,0]]) # an example to estimate a particular y#