In [1]:
import pandas as pd
import numpy as np

In [ ]:
dm=pd.read_excel(r"C:\Users\anadi\Desktop\Direct Marketing - Classification.xlsx")

In [ ]:
dm.shape

In [5]:
dm.head()

,AmountSpent,Age,Gender,OwnHome,Married,Location,Salary,Children,Catalogs,History
0,Low,Old,Female,Own,Single,Far,47500,0,6,High
1,High,Middle,Male,Rent,Single,Close,63600,0,6,High
2,Low,Young,Female,Rent,Single,Close,13500,0,18,Low
3,High,Middle,Male,Own,Married,Close,85600,1,18,High
4,High,Middle,Female,Own,Single,Close,68400,0,12,High

In [9]:
dm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   AmountSpent  1000 non-null   object
 1   Age          1000 non-null   object
 2   Gender       1000 non-null   object
 3   OwnHome      1000 non-null   object
 4   Married      1000 non-null   object
 5   Location     1000 non-null   object
 6   Salary       1000 non-null   int64
 7   Children     1000 non-null   int64
 8   Catalogs     1000 non-null   int64
 9   History      1000 non-null   object
dtypes: int64(3), object(7)
memory usage: 78.3+ KB

In [7]:
dm["History"]=dm["History"].astype("category")
dm["History"]=dm["History"].cat.codes

In [9]:
dm["Location"]=dm["Location"].astype("category")
dm["Location"]=dm["Location"].cat.codes

In [11]:
dm["Married"]=dm["Married"].astype("category")
dm["Married"]=dm["Married"].cat.codes

In [13]:
dm["OwnHome"]=dm["OwnHome"].astype("category")
dm["OwnHome"]=dm["OwnHome"].cat.codes

In [17]:
dm["Gender"]=dm["Gender"].astype("category")
dm["Gender"]=dm["Gender"].cat.codes

In [21]:
dm["Age"]=dm["Age"].astype("category")
dm["Age"]=dm["Age"].cat.codes

In [23]:
dm["AmountSpent"]=dm["AmountSpent"].astype("category")
dm["AmountSpent"]=dm["AmountSpent"].cat.codes

In [255]:
dm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   AmountSpent  1000 non-null   int8
 1   Age          1000 non-null   int8
 2   Gender       1000 non-null   int8
 3   OwnHome      1000 non-null   int8
 4   Married      1000 non-null   int8
 5   Location     1000 non-null   int8
 6   Salary       1000 non-null   int64
 7   Children     1000 non-null   int64
 8   Catalogs     1000 non-null   int64
 9   History      1000 non-null   int8
dtypes: int64(3), int8(7)
memory usage: 30.4 KB

In [25]:
dm.head()

,AmountSpent,Age,Gender,OwnHome,Married,Location,Salary,Children,Catalogs,History
0,1,1,0,0,1,1,47500,0,6,1
1,0,0,1,1,1,0,63600,0,6,1
2,1,2,0,1,1,0,13500,0,18,2
3,0,0,1,0,0,0,85600,1,18,1
4,0,0,0,0,1,0,68400,0,12,1

In [25]:
x=dm.iloc[:,1:10]

In [29]:
x

,Age,Gender,OwnHome,Married,Location,Salary,Children,Catalogs,History
0,1,0,0,1,1,47500,0,6,1
1,0,1,1,1,0,63600,0,6,1
2,2,0,1,1,0,13500,0,18,2
3,0,1,0,0,0,85600,1,18,1
4,0,0,0,1,0,68400,0,12,1
...,...,...,...,...,...,...,...,...,...
995,2,0,1,1,0,19400,1,18,0
996,0,1,1,1,1,40500,1,18,0
997,1,1,0,1,0,44800,0,24,3
998,0,1,0,0,0,79000,2,18,3
999,2,1,1,0,0,53600,1,24,3

In [27]:
y=dm.iloc[:,0:1]

In [33]:
y

     AmountSpent
0              1
1              0
2              1
3              0
4              0
..           ...
995            1
996            0
997            0
998            1
999            0

[1000 rows x 1 columns]

In [29]:
import sklearn

In [31]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=24)

In [ ]:
dm.shape

In [39]:
xtrain.shape

(700, 9)

In [41]:
ytrain.shape

(700, 1)

In [ ]:
xtest.shape

In [ ]:
ytest.shape

In [33]:
from sklearn.preprocessing import StandardScaler

In [35]:
scaler=StandardScaler()

In [41]:
xtrain_scaled=scaler.fit_transform(xtrain)

In [43]:
xtest_scaled=scaler.transform(xtest)

In [45]:
from sklearn import linear_model

In [47]:
from sklearn.linear_model import LogisticRegression

In [49]:
log_reg=LogisticRegression()

In [51]:
log_reg.fit(xtrain_scaled,ytrain)

C:\Users\Bianka\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [53]:
ypred=log_reg.predict(xtest_scaled)

In [67]:
ypred

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1], dtype=int8)

In [69]:
log_reg.score(xtrain_scaled,ytrain)

0.8785714285714286

In [71]:
log_reg.score(xtest_scaled,ytest)

0.8766666666666667

In [299]:
import sklearn.metrics as metrics

In [301]:
from sklearn.metrics import confusion_matrix

In [313]:
confusion_matrix(ytest,ypred)

array([[129,  23],
       [ 14, 134]], dtype=int64)