In [1]:
import pandas as pd
import numpy as np

In [ ]:
dm=pd.read_excel(r"C:\Users\anadi\Desktop\Direct Marketing.xlsx")

In [ ]:
dm.shape

In [5]:
dm.head()

,AmountSpent,Age,Gender,OwnHome,Married,Location,Salary,Children,Catalogs,History
0,755,Old,Female,Own,Single,Far,47500,0,6,High
1,1318,Middle,Male,Rent,Single,Close,63600,0,6,High
2,296,Young,Female,Rent,Single,Close,13500,0,18,Low
3,2436,Middle,Male,Own,Married,Close,85600,1,18,High
4,1304,Middle,Female,Own,Single,Close,68400,0,12,High

In [7]:
dm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   AmountSpent  1000 non-null   int64
 1   Age          1000 non-null   object
 2   Gender       1000 non-null   object
 3   OwnHome      1000 non-null   object
 4   Married      1000 non-null   object
 5   Location     1000 non-null   object
 6   Salary       1000 non-null   int64
 7   Children     1000 non-null   int64
 8   Catalogs     1000 non-null   int64
 9   History      1000 non-null   object
dtypes: int64(4), object(6)
memory usage: 78.3+ KB

In [9]:
dm_cat=dm.select_dtypes(object)

In [11]:
dm_num=dm.select_dtypes(int)

In [11]:
dm_num

     AmountSpent  Salary  Children  Catalogs
0            755   47500         0         6
1           1318   63600         0         6
2            296   13500         0        18
3           2436   85600         1        18
4           1304   68400         0        12
..           ...     ...       ...       ...
995          384   19400         1        18
996         1073   40500         1        18
997         1417   44800         0        24
998          671   79000         2        18
999          973   53600         1        24

[1000 rows x 4 columns]

In [13]:
dm_cat

        Age  Gender OwnHome  Married Location     History
0       Old  Female     Own   Single      Far        High
1    Middle    Male    Rent   Single    Close        High
2     Young  Female    Rent   Single    Close         Low
3    Middle    Male     Own  Married    Close        High
4    Middle  Female     Own   Single    Close        High
..      ...     ...     ...      ...      ...         ...
995   Young  Female    Rent   Single    Close  First time
996  Middle    Male    Rent   Single      Far  First time
997     Old    Male     Own   Single    Close      Medium
998  Middle    Male     Own  Married    Close      Medium
999   Young    Male    Rent  Married    Close      Medium

[1000 rows x 6 columns]

In [13]:
dummies = pd.get_dummies(dm_cat)

In [15]:
dummies

,Age_Middle,Age_Old,Age_Young,Gender_Female,Gender_Male,OwnHome_Own,OwnHome_Rent,Married_Married,Married_Single,Location_Close,Location_Far,History_First time,History_High,History_Low,History_Medium
0,False,True,False,True,False,True,False,False,True,False,True,False,True,False,False
1,True,False,False,False,True,False,True,False,True,True,False,False,True,False,False
2,False,False,True,True,False,False,True,False,True,True,False,False,False,True,False
3,True,False,False,False,True,True,False,True,False,True,False,False,True,False,False
4,True,False,False,True,False,True,False,False,True,True,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,True,True,False,False,True,False,True,True,False,True,False,False,False
996,True,False,False,False,True,False,True,False,True,False,True,True,False,False,False
997,False,True,False,False,True,True,False,False,True,True,False,False,False,False,True
998,True,False,False,False,True,True,False,True,False,True,False,False,False,False,True
999,False,False,True,False,True,False,True,True,False,True,False,False,False,False,True

In [17]:
dm1=pd.concat([dm,dummies],axis="columns")

In [19]:
dm1.head()

,AmountSpent,Age,Gender,OwnHome,Married,Location,Salary,Children,Catalogs,History,...,OwnHome_Own,OwnHome_Rent,Married_Married,Married_Single,Location_Close,Location_Far,History_First time,History_High,History_Low,History_Medium
0,755,Old,Female,Own,Single,Far,47500,0,6,High,...,True,False,False,True,False,True,False,True,False,False
1,1318,Middle,Male,Rent,Single,Close,63600,0,6,High,...,False,True,False,True,True,False,False,True,False,False
2,296,Young,Female,Rent,Single,Close,13500,0,18,Low,...,False,True,False,True,True,False,False,False,True,False
3,2436,Middle,Male,Own,Married,Close,85600,1,18,High,...,True,False,True,False,True,False,False,True,False,False
4,1304,Middle,Female,Own,Single,Close,68400,0,12,High,...,True,False,False,True,True,False,False,True,False,False

In [21]:
dm2=dm1.drop(["Age","Gender","OwnHome","Married","Location","History"],axis="columns")

In [23]:
dm2.head()

,AmountSpent,Salary,Children,Catalogs,Age_Middle,Age_Old,Age_Young,Gender_Female,Gender_Male,OwnHome_Own,OwnHome_Rent,Married_Married,Married_Single,Location_Close,Location_Far,History_First time,History_High,History_Low,History_Medium
0,755,47500,0,6,False,True,False,True,False,True,False,False,True,False,True,False,True,False,False
1,1318,63600,0,6,True,False,False,False,True,False,True,False,True,True,False,False,True,False,False
2,296,13500,0,18,False,False,True,True,False,False,True,False,True,True,False,False,False,True,False
3,2436,85600,1,18,True,False,False,False,True,True,False,True,False,True,False,False,True,False,False
4,1304,68400,0,12,True,False,False,True,False,True,False,False,True,True,False,False,True,False,False

In [25]:
x=dm2.iloc[:,1:19]

In [ ]:
x

In [27]:
y=dm.iloc[:,0:1]

In [ ]:
y

In [29]:
import sklearn

In [29]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=24)

In [ ]:
xtrain.shape

In [ ]:
ytrain.shape

In [ ]:
xtest.shape

In [ ]:
ytest.shape

In [31]:
from sklearn import tree

In [33]:
from sklearn.tree import DecisionTreeRegressor

In [35]:
dt=DecisionTreeRegressor()

In [37]:
dt=dt.fit(xtrain,ytrain)

In [39]:
ypred=dt.predict(xtest)

In [ ]:
ypred

In [41]:
text_form=tree.export_text(dt)   
print(text_form)

|--- feature_0 <= 66050.00
|   |--- feature_0 <= 32650.00
|   |   |--- feature_0 <= 19350.00
|   |   |   |--- feature_2 <= 9.00
|   |   |   |   |--- feature_13 <= 0.50
|   |   |   |   |   |--- feature_14 <= 0.50
|   |   |   |   |   |   |--- feature_1 <= 1.50
|   |   |   |   |   |   |   |--- feature_0 <= 12300.00
|   |   |   |   |   |   |   |   |--- value: [90.00]
|   |   |   |   |   |   |   |--- feature_0 >  12300.00
|   |   |   |   |   |   |   |   |--- feature_0 <= 16250.00
|   |   |   |   |   |   |   |   |   |--- feature_7 <= 0.50
|   |   |   |   |   |   |   |   |   |   |--- feature_0 <= 12700.00
|   |   |   |   |   |   |   |   |   |   |   |--- value: [202.00]
|   |   |   |   |   |   |   |   |   |   |--- feature_0 >  12700.00
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 6
|   |   |   |   |   |   |   |   |   |--- feature_7 >  0.50
|   |   |   |   |   |   |   |   |   |   |--- feature_0 <= 14800.00
|   |   |   |   |   |   |   |   |   |   |   |--- value: [250.00]
|   |   |   |   |   |   |   |   |   |   |--- feature_0 >  14800.00
|   |   |   |   |   |   |   |   |   |   |   |--- value: [172.00]
|   |   |   |   |   |   |   |   |--- feature_0 >  16250.00
|   |   |   |   |   |   |   |   |   |--- feature_0 <= 17900.00
|   |   |   |   |   |   |   |   |   |   |--- value: [247.00]
|   |   |   |   |   |   |   |   |   |--- feature_0 >  17900.00
|   |   |   |   |   |   |   |   |   |   |--- value: [184.00]
|   |   |   |   |   |   |--- feature_1 >  1.50
|   |   |   |   |   |   |   |--- feature_7 <= 0.50
|   |   |   |   |   |   |   |   |--- feature_4 <= 0.50
|   |   |   |   |   |   |   |   |   |--- feature_0 <= 16250.00
|   |   |   |   |   |   |   |   |   |   |--- value: [47.00]
|   |   |   |   |   |   |   |   |   |--- feature_0 >  16250.00
|   |   |   |   |   |   |   |   |   |   |--- value: [62.00]
|   |   |   |   |   |   |   |   |--- feature_4 >  0.50
|   |   |   |   |   |   |   |   |   |--- value: [65.00]
|   |   |   |   |   |   |   |--- feature_7 >  0.50
|   |   |   |   |   |   |   |   |--- feature_0 <= 14000.00
|   |   |   |   |   |   |   |   |   |--- value: [43.00]
|   |   |   |   |   |   |   |   |--- feature_0 >  14000.00
|   |   |   |   |   |   |   |   |   |--- value: [38.00]
|   |   |   |   |   |--- feature_14 >  0.50
|   |   |   |   |   |   |--- feature_0 <= 14350.00
|   |   |   |   |   |   |   |--- feature_7 <= 0.50
|   |   |   |   |   |   |   |   |--- feature_0 <= 13500.00
|   |   |   |   |   |   |   |   |   |--- feature_1 <= 1.50
|   |   |   |   |   |   |   |   |   |   |--- feature_4 <= 0.50
|   |   |   |   |   |   |   |   |   |   |   |--- value: [236.00]
|   |   |   |   |   |   |   |   |   |   |--- feature_4 >  0.50
|   |   |   |   |   |   |   |   |   |   |   |--- value: [258.00]
|   |   |   |   |   |   |   |   |   |--- feature_1 >  1.50
|   |   |   |   |   |   |   |   |   |   |--- feature_0 <= 10800.00
|   |   |   |   |   |   |   |   |   |   |   |--- value: [199.00]
|   |   |   |   |   |   |   |   |   |   |--- feature_0 >  10800.00
|   |   |   |   |   |   |   |   |   |   |   |--- value: [186.00]
|   |   |   |   |   |   |   |   |--- feature_0 >  13500.00
|   |   |   |   |   |   |   |   |   |--- feature_1 <= 2.00
|   |   |   |   |   |   |   |   |   |   |--- value: [163.00]
|   |   |   |   |   |   |   |   |   |--- feature_1 >  2.00
|   |   |   |   |   |   |   |   |   |   |--- value: [153.00]
|   |   |   |   |   |   |   |--- feature_7 >  0.50
|   |   |   |   |   |   |   |   |--- value: [106.00]
|   |   |   |   |   |   |--- feature_0 >  14350.00
|   |   |   |   |   |   |   |--- feature_1 <= 2.50
|   |   |   |   |   |   |   |   |--- feature_0 <= 17250.00
|   |   |   |   |   |   |   |   |   |--- value: [281.00]
|   |   |   |   |   |   |   |   |--- feature_0 >  17250.00
|   |   |   |   |   |   |   |   |   |--- value: [259.00]
|   |   |   |   |   |   |   |--- feature_1 >  2.50
|   |   |   |   |   |   |   |   |--- value: [307.00]
|   |   |   |   |--- feature_13 >  0.50
|   |   |   |   |   |--- feature_0 <= 16200.00
|   |   |   |   |   |   |--- feature_5 <= 0.50
|   |   |   |   |   |   |   |--- feature_6 <= 0.50
|   |   |   |   |   |   |   |   |--- value: [297.00]
|   |   |   |   |   |   |   |--- feature_6 >  0.50
|   |   |   |   |   |   |   |   |--- value: [348.00]
|   |   |   |   |   |   |--- feature_5 >  0.50
|   |   |   |   |   |   |   |--- feature_0 <= 13450.00
|   |   |   |   |   |   |   |   |--- value: [241.00]
|   |   |   |   |   |   |   |--- feature_0 >  13450.00
|   |   |   |   |   |   |   |   |--- feature_0 <= 14400.00
|   |   |   |   |   |   |   |   |   |--- value: [194.00]
|   |   |   |   |   |   |   |   |--- feature_0 >  14400.00
|   |   |   |   |   |   |   |   |   |--- feature_16 <= 0.50
|   |   |   |   |   |   |   |   |   |   |--- value: [202.00]
|   |   |   |   |   |   |   |   |   |--- feature_16 >  0.50
|   |   |   |   |   |   |   |   |   |   |--- value: [222.00]
|   |   |   |   |   |--- feature_0 >  16200.00
|   |   |   |   |   |   |--- feature_0 <= 16800.00
|   |   |   |   |   |   |   |--- value: [317.00]
|   |   |   |   |   |   |--- feature_0 >  16800.00
|   |   |   |   |   |   |   |--- feature_1 <= 0.50
|   |   |   |   |   |   |   |   |--- value: [411.00]
|   |   |   |   |   |   |   |--- feature_1 >  0.50
|   |   |   |   |   |   |   |   |--- value: [319.00]
|   |   |   |--- feature_2 >  9.00
|   |   |   |   |--- feature_1 <= 1.50
|   |   |   |   |   |--- feature_12 <= 0.50
|   |   |   |   |   |   |--- feature_2 <= 15.00
|   |   |   |   |   |   |   |--- feature_14 <= 0.50
|   |   |   |   |   |   |   |   |--- feature_6 <= 0.50
|   |   |   |   |   |   |   |   |   |--- value: [368.00]
|   |   |   |   |   |   |   |   |--- feature_6 >  0.50
|   |   |   |   |   |   |   |   |   |--- value: [378.00]
|   |   |   |   |   |   |   |--- feature_14 >  0.50
|   |   |   |   |   |   |   |   |--- feature_8 <= 0.50
|   |   |   |   |   |   |   |   |   |--- feature_1 <= 0.50
|   |   |   |   |   |   |   |   |   |   |--- value: [428.00]
|   |   |   |   |   |   |   |   |   |--- feature_1 >  0.50
|   |   |   |   |   |   |   |   |   |   |--- value: [422.00]
|   |   |   |   |   |   |   |   |--- feature_8 >  0.50
|   |   |   |   |   |   |   |   |   |--- value: [360.00]
|   |   |   |   |   |   |--- feature_2 >  15.00
|   |   |   |   |   |   |   |--- feature_0 <= 17600.00
|   |   |   |   |   |   |   |   |--- feature_1 <= 0.50
|   |   |   |   |   |   |   |   |   |--- feature_0 <= 13550.00
|   |   |   |   |   |   |   |   |   |   |--- feature_2 <= 21.00
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- feature_2 >  21.00
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |--- feature_0 >  13550.00
|   |   |   |   |   |   |   |   |   |   |--- feature_2 <= 21.00
|   |   |   |   |   |   |   |   |   |   |   |--- value: [472.00]
|   |   |   |   |   |   |   |   |   |   |--- feature_2 >  21.00
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |--- feature_1 >  0.50
|   |   |   |   |   |   |   |   |   |--- feature_0 <= 15450.00
|   |   |   |   |   |   |   |   |   |   |--- value: [349.00]
|   |   |   |   |   |   |   |   |   |--- feature_0 >  15450.00
|   |   |   |   |   |   |   |   |   |   |--- value: [381.00]
|   |   |   |   |   |   |   |--- feature_0 >  17600.00
|   |   |   |   |   |   |   |   |--- value: [742.00]
|   |   |   |   |   |--- feature_12 >  0.50
|   |   |   |   |   |   |--- feature_0 <= 13300.00
|   |   |   |   |   |   |   |--- feature_0 <= 10300.00
|   |   |   |   |   |   |   |   |--- value: [362.00]
|   |   |   |   |   |   |   |--- feature_0 >  10300.00
|   |   |   |   |   |   |   |   |--- feature_0 <= 11850.00
|   |   |   |   |   |   |   |   |   |--- feature_7 <= 0.50
|   |   |   |   |   |   |   |   |   |   |--- feature_4 <= 0.50
|   |   |   |   |   |   |   |   |   |   |   |--- value: [193.00]
|   |   |   |   |   |   |   |   |   |   |--- feature_4 >  0.50
|   |   |   |   |   |   |   |   |   |   |   |--- value: [195.00]
|   |   |   |   |   |   |   |   |   |--- feature_7 >  0.50
|   |   |   |   |   |   |   |   |   |   |--- value: [189.00]
|   |   |   |   |   |   |   |   |--- feature_0 >  11850.00
|   |   |   |   |   |   |   |   |   |--- feature_1 <= 0.50
|   |   |   |   |   |   |   |   |   |   |--- value: [344.00]
|   |   |   |   |   |   |   |   |   |--- feature_1 >  0.50
|   |   |   |   |   |   |   |   |   |   |--- value: [227.00]
|   |   |   |   |   |   |--- feature_0 >  13300.00
|   |   |   |   |   |   |   |--- feature_2 <= 15.00
|   |   |   |   |   |   |   |   |--- feature_1 <= 0.50
|   |   |   |   |   |   |   |   |   |--- feature_4 <= 0.50
|   |   |   |   |   |   |   |   |   |   |--- feature_0 <= 18450.00
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 5
|   |   |   |   |   |   |   |   |   |   |--- feature_0 >  18450.00
|   |   |   |   |   |   |   |   |   |   |   |--- value: [289.00]
|   |   |   |   |   |   |   |   |   |--- feature_4 >  0.50
|   |   |   |   |   |   |   |   |   |   |--- value: [275.00]
|   |   |   |   |   |   |   |   |--- feature_1 >  0.50
|   |   |   |   |   |   |   |   |   |--- feature_16 <= 0.50
|   |   |   |   |   |   |   |   |   |   |--- value: [329.00]
|   |   |   |   |   |   |   |   |   |--- feature_16 >  0.50
|   |   |   |   |   |   |   |   |   |   |--- feature_6 <= 0.50
|   |   |   |   |   |   |   |   |   |   |   |--- value: [268.00]
|   |   |   |   |   |   |   |   |   |   |--- feature_6 >  0.50
|   |   |   |   |   |   |   |   |   |   |   |--- value: [218.00]
|   |   |   |   |   |   |   |--- feature_2 >  15.00
|   |   |   |   |   |   |   |   |--- feature_14 <= 0.50
|   |   |   |   |   |   |   |   |   |--- feature_0 <= 14500.00
|   |   |   |   |   |   |   |   |   |   |--- feature_7 <= 0.50
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- feature_7 >  0.50
|   |   |   |   |   |   |   |   |   |   |   |--- value: [424.00]
|   |   |   |   |   |   |   |   |   |--- feature_0 >  14500.00
|   |   |   |   |   |   |   |   |   |   |--- feature_0 <= 16850.00
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3
|   |   |   |   |   |   |   |   |   |   |--- feature_0 >  16850.00
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3
|   |   |   |   |   |   |   |   |--- feature_14 >  0.50
|   |   |   |   |   |   |   |   |   |--- feature_0 <= 14350.00
|   |   |   |   |   |   |   |   |   |   |--- feature_7 <= 0.50
|   |   |   |   |   |   |   |   |   |   |   |--- value: [458.00]
|   |   |   |   |   |   |   |   |   |   |--- feature_7 >  0.50
|   |   |   |   |   |   |   |   |   |   |   |--- value: [400.00]
|   |   |   |   |   |   |   |   |   |--- feature_0 >  14350.00
|   |   |   |   |   |   |   |   |   |   |--- feature_6 <= 0.50
|   |   |   |   |   |   |   |   |   |   |   |--- value: [615.00]
|   |   |   |   |   |   |   |   |   |   |--- feature_6 >  0.50
|   |   |   |   |   |   |   |   |   |   |   |--- value: [406.00]
|   |   |   |   |--- feature_1 >  1.50
|   |   |   |   |   |--- feature_16 <= 0.50
|   |   |   |   |   |   |--- feature_2 <= 21.00
|   |   |   |   |   |   |   |--- feature_1 <= 2.50
|   |   |   |   |   |   |   |   |--- feature_2 <= 15.00
|   |   |   |   |   |   |   |   |   |--- feature_7 <= 0.50
|   |   |   |   |   |   |   |   |   |   |--- value: [341.00]
|   |   |   |   |   |   |   |   |   |--- feature_7 >  0.50
|   |   |   |   |   |   |   |   |   |   |--- value: [333.00]
|   |   |   |   |   |   |   |   |--- feature_2 >  15.00
|   |   |   |   |   |   |   |   |   |--- value: [393.00]
|   |   |   |   |   |   |   |--- feature_1 >  2.50
|   |   |   |   |   |   |   |   |--- feature_0 <= 11950.00
|   |   |   |   |   |   |   |   |   |--- value: [312.00]
|   |   |   |   |   |   |   |   |--- feature_0 >  11950.00
|   |   |   |   |   |   |   |   |   |--- value: [206.00]
|   |   |   |   |   |   |--- feature_2 >  21.00
|   |   |   |   |   |   |   |--- value: [517.00]
|   |   |   |   |   |--- feature_16 >  0.50
|   |   |   |   |   |   |--- feature_12 <= 0.50
|   |   |   |   |   |   |   |--- feature_0 <= 15850.00
|   |   |   |   |   |   |   |   |--- feature_0 <= 12950.00
|   |   |   |   |   |   |   |   |   |--- feature_1 <= 2.50
|   |   |   |   |   |   |   |   |   |   |--- value: [213.00]
|   |   |   |   |   |   |   |   |   |--- feature_1 >  2.50
|   |   |   |   |   |   |   |   |   |   |--- value: [205.00]
|   |   |   |   |   |   |   |   |--- feature_0 >  12950.00
|   |   |   |   |   |   |   |   |   |--- value: [160.00]
|   |   |   |   |   |   |   |--- feature_0 >  15850.00
|   |   |   |   |   |   |   |   |--- value: [322.00]
|   |   |   |   |   |   |--- feature_12 >  0.50
|   |   |   |   |   |   |   |--- feature_2 <= 15.00
|   |   |   |   |   |   |   |   |--- feature_7 <= 0.50
|   |   |   |   |   |   |   |   |   |--- feature_0 <= 13650.00
|   |   |   |   |   |   |   |   |   |   |--- value: [114.00]
|   |   |   |   |   |   |   |   |   |--- feature_0 >  13650.00
|   |   |   |   |   |   |   |   |   |   |--- value: [108.00]
|   |   |   |   |   |   |   |   |--- feature_7 >  0.50
|   |   |   |   |   |   |   |   |   |--- value: [147.00]
|   |   |   |   |   |   |   |--- feature_2 >  15.00
|   |   |   |   |   |   |   |   |--- feature_0 <= 16500.00
|   |   |   |   |   |   |   |   |   |--- value: [197.00]
|   |   |   |   |   |   |   |   |--- feature_0 >  16500.00
|   |   |   |   |   |   |   |   |   |--- value: [170.00]
|   |   |--- feature_0 >  19350.00
|   |   |   |--- feature_2 <= 15.00
|   |   |   |   |--- feature_14 <= 0.50
|   |   |   |   |   |--- feature_1 <= 0.50
|   |   |   |   |   |   |--- feature_0 <= 27850.00
|   |   |   |   |   |   |   |--- feature_13 <= 0.50
|   |   |   |   |   |   |   |   |--- feature_0 <= 22700.00
|   |   |   |   |   |   |   |   |   |--- feature_0 <= 20100.00
|   |   |   |   |   |   |   |   |   |   |--- value: [395.00]
|   |   |   |   |   |   |   |   |   |--- feature_0 >  20100.00
|   |   |   |   |   |   |   |   |   |   |--- feature_0 <= 20900.00
|   |   |   |   |   |   |   |   |   |   |   |--- value: [201.00]
|   |   |   |   |   |   |   |   |   |   |--- feature_0 >  20900.00
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |--- feature_0 >  22700.00
|   |   |   |   |   |   |   |   |   |--- feature_0 <= 23950.00
|   |   |   |   |   |   |   |   |   |   |--- value: [371.00]
|   |   |   |   |   |   |   |   |   |--- feature_0 >  23950.00
|   |   |   |   |   |   |   |   |   |   |--- feature_11 <= 0.50
|   |   |   |   |   |   |   |   |   |   |   |--- value: [435.00]
|   |   |   |   |   |   |   |   |   |   |--- feature_11 >  0.50
|   |   |   |   |   |   |   |   |   |   |   |--- value: [491.00]
|   |   |   |   |   |   |   |--- feature_13 >  0.50
|   |   |   |   |   |   |   |   |--- feature_7 <= 0.50
|   |   |   |   |   |   |   |   |   |--- value: [535.00]
|   |   |   |   |   |   |   |   |--- feature_7 >  0.50
|   |   |   |   |   |   |   |   |   |--- value: [563.00]
|   |   |   |   |   |   |--- feature_0 >  27850.00
|   |   |   |   |   |   |   |--- feature_0 <= 28950.00
|   |   |   |   |   |   |   |   |--- value: [830.00]
|   |   |   |   |   |   |   |--- feature_0 >  28950.00
|   |   |   |   |   |   |   |   |--- value: [482.00]
|   |   |   |   |   |--- feature_1 >  0.50
|   |   |   |   |   |   |--- feature_12 <= 0.50
|   |   |   |   |   |   |   |--- feature_0 <= 20200.00
|   |   |   |   |   |   |   |   |--- value: [330.00]
|   |   |   |   |   |   |   |--- feature_0 >  20200.00
|   |   |   |   |   |   |   |   |--- feature_0 <= 21900.00
|   |   |   |   |   |   |   |   |   |--- value: [550.00]
|   |   |   |   |   |   |   |   |--- feature_0 >  21900.00
|   |   |   |   |   |   |   |   |   |--- value: [457.00]
|   |   |   |   |   |   |--- feature_12 >  0.50
|   |   |   |   |   |   |   |--- feature_1 <= 1.50
|   |   |   |   |   |   |   |   |--- feature_0 <= 31850.00
|   |   |   |   |   |   |   |   |   |--- feature_4 <= 0.50
|   |   |   |   |   |   |   |   |   |   |--- feature_0 <= 29750.00
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 5
|   |   |   |   |   |   |   |   |   |   |--- feature_0 >  29750.00
|   |   |   |   |   |   |   |   |   |   |   |--- value: [357.00]
|   |   |   |   |   |   |   |   |   |--- feature_4 >  0.50
|   |   |   |   |   |   |   |   |   |   |--- value: [161.00]
|   |   |   |   |   |   |   |   |--- feature_0 >  31850.00
|   |   |   |   |   |   |   |   |   |--- value: [515.00]
|   |   |   |   |   |   |   |--- feature_1 >  1.50
|   |   |   |   |   |   |   |   |--- feature_10 <= 0.50
|   |   |   |   |   |   |   |   |   |--- feature_0 <= 22750.00
|   |   |   |   |   |   |   |   |   |   |--- value: [209.00]
|   |   |   |   |   |   |   |   |   |--- feature_0 >  22750.00
|   |   |   |   |   |   |   |   |   |   |--- feature_3 <= 0.50
|   |   |   |   |   |   |   |   |   |   |   |--- value: [172.00]
|   |   |   |   |   |   |   |   |   |   |--- feature_3 >  0.50
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |--- feature_10 >  0.50
|   |   |   |   |   |   |   |   |   |--- value: [139.00]
|   |   |   |   |--- feature_14 >  0.50
|   |   |   |   |   |--- feature_0 <= 22150.00
|   |   |   |   |   |   |--- feature_0 <= 21150.00
|   |   |   |   |   |   |   |--- feature_12 <= 0.50
|   |   |   |   |   |   |   |   |--- value: [260.00]
|   |   |   |   |   |   |   |--- feature_12 >  0.50
|   |   |   |   |   |   |   |   |--- value: [296.00]
|   |   |   |   |   |   |--- feature_0 >  21150.00
|   |   |   |   |   |   |   |--- feature_12 <= 0.50
|   |   |   |   |   |   |   |   |--- value: [326.00]
|   |   |   |   |   |   |   |--- feature_12 >  0.50
|   |   |   |   |   |   |   |   |--- feature_1 <= 1.00
|   |   |   |   |   |   |   |   |   |--- value: [414.00]
|   |   |   |   |   |   |   |   |--- feature_1 >  1.00
|   |   |   |   |   |   |   |   |   |--- value: [387.00]
|   |   |   |   |   |--- feature_0 >  22150.00
|   |   |   |   |   |   |--- feature_12 <= 0.50
|   |   |   |   |   |   |   |--- feature_11 <= 0.50
|   |   |   |   |   |   |   |   |--- value: [452.00]
|   |   |   |   |   |   |   |--- feature_11 >  0.50
|   |   |   |   |   |   |   |   |--- feature_8 <= 0.50
|   |   |   |   |   |   |   |   |   |--- value: [865.00]
|   |   |   |   |   |   |   |   |--- feature_8 >  0.50
|   |   |   |   |   |   |   |   |   |--- feature_0 <= 28750.00
|   |   |   |   |   |   |   |   |   |   |--- value: [576.00]
|   |   |   |   |   |   |   |   |   |--- feature_0 >  28750.00
|   |   |   |   |   |   |   |   |   |   |--- value: [774.00]
|   |   |   |   |   |   |--- feature_12 >  0.50
|   |   |   |   |   |   |   |--- feature_0 <= 28500.00
|   |   |   |   |   |   |   |   |--- feature_0 <= 23300.00
|   |   |   |   |   |   |   |   |   |--- value: [521.00]
|   |   |   |   |   |   |   |   |--- feature_0 >  23300.00
|   |   |   |   |   |   |   |   |   |--- feature_0 <= 24550.00
|   |   |   |   |   |   |   |   |   |   |--- value: [362.00]
|   |   |   |   |   |   |   |   |   |--- feature_0 >  24550.00
|   |   |   |   |   |   |   |   |   |   |--- feature_8 <= 0.50
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 5
|   |   |   |   |   |   |   |   |   |   |--- feature_8 >  0.50
|   |   |   |   |   |   |   |   |   |   |   |--- value: [408.00]
|   |   |   |   |   |   |   |--- feature_0 >  28500.00
|   |   |   |   |   |   |   |   |--- feature_0 <= 30600.00
|   |   |   |   |   |   |   |   |   |--- feature_6 <= 0.50
|   |   |   |   |   |   |   |   |   |   |--- value: [583.00]
|   |   |   |   |   |   |   |   |   |--- feature_6 >  0.50
|   |   |   |   |   |   |   |   |   |   |--- value: [636.00]
|   |   |   |   |   |   |   |   |--- feature_0 >  30600.00
|   |   |   |   |   |   |   |   |   |--- value: [476.00]
|   |   |   |--- feature_2 >  15.00
|   |   |   |   |--- feature_16 <= 0.50

In [41]:
x.columns

Index(['Salary', 'Children', 'Catalogs', 'Age_Middle', 'Age_Old', 'Age_Young',
       'Gender_Female', 'Gender_Male', 'OwnHome_Own', 'OwnHome_Rent',
       'Married_Married', 'Married_Single', 'Location_Close', 'Location_Far',
       'History_First time', 'History_High', 'History_Low', 'History_Medium'],
      dtype='object')

In [43]:
features=pd.DataFrame(dt.feature_importances_,index=x.columns)

In [45]:
features

                           0
Salary              0.561384
Children            0.077906
Catalogs            0.157151
Age_Middle          0.006066
Age_Old             0.008631
Age_Young           0.000244
Gender_Female       0.003824
Gender_Male         0.002625
OwnHome_Own         0.004742
OwnHome_Rent        0.001210
Married_Married     0.003697
Married_Single      0.000548
Location_Close      0.006767
Location_Far        0.036440
History_First time  0.022606
History_High        0.014378
History_Low         0.036826
History_Medium      0.054953

In [ ]:
import sklearn.metrics as metrics

In [ ]:
mae = metrics.mean_absolute_error(ytest, ypred)
mse = metrics.mean_squared_error(ytest, ypred)

In [ ]:
mae

In [ ]:
mse

In [ ]:
m = np.mean(ytest)

In [ ]:
d = ytest-m

In [ ]:
mae_base = np.mean(abs(d))
mse_base = np.mean(d**2)

In [ ]:
mae_base

In [ ]:
mse_base